region: us-west-2

function_name: pizza
handler: service.handler
role: pylambda-role
description: My first lambda function

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id: 
aws_secret_access_key: 

# dist_directory: dist
# timeout: 15
# memory_size: 512
